#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www.

subdomains=("www" "lb-01" "web-01" "web-02")
func ()
{
	data=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | tr '\n' ' ')
    echo "$2 $data" | awk '{print "The subdomain " $1 " is a "$5" record and points to "$6}'
}

if [ -z "$2" ]
then
	for subdomain in ${subdomains[@]}
	do
    func "$1" "$subdomain"
    done
else
	func "$1" "$2"
fi