#!/usr/bin/env bash
# Install Nginx on own server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" > /var/www/html/index.nginx-debian.html