#!/usr/bin/env bash
# Install Nginx on own server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html