#!/usr/bin/env bash
# Install Nginx on own server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
NEW="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"
sed -i "/server_name _;/ a\\$NEW" /etc/nginx/sites-available/default
sudo service nginx restart