#!/usr/bin/env bash
# Install Nginx on own server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/listen 80 default_server;\rewrite ^/redirect_me https://github.com/jyuly12 permanent;/" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server; \n\terror_page 404 /404.html;/" /etc/nginx/sites-available/default
sudo service nginx restart