#!/usr/bin/env bash
# Install Nginx on own server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "48i add_header X-Served-By $HOSTNAME always;" /etc/nginx/sites-available/default
sudo service nginx restart