#!/usr/bin/env bash
# This is an script that displays Holberton School 10 times, but for the 9th
# iteration, displays Holberton School and then Hi
i=1
while ((i <= 10)); do
      echo "Holberton School"
      if ((i == 9)); then
      	 echo "Hi"
      fi
      ((i++))
done