#!/usr/bin/env bash
# gives you information about the holbertonschool file.

f="holbertonschool"
if [ -e $f ]; then
    echo "$f file exists"
    if [ ! -s $f ]; then
	echo "$f file is empty"
    elif [ -s $f ]; then
	echo "$f file is not empty"
    fi
    if [ -f $f ]; then
	echo "$f is a regular file"
    fi
else
    echo "$f file does not exist"
fi
